/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProductSetObjectPageObjectPage journey");

        opaTest("Navigate to ProductSetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheProductSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheProductSetListGenerated.onTable().iCheckRows();
            When.onTheProductSetListGenerated.onTable().iPressRow(0);

            Then.onTheProductSetObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheProductSetObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductId" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductName" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Category" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SupplierId" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SupplierName" });
            Then.onTheProductSetObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Country" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});