/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrderItemSetObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseOrderItemSetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePurchaseOrderSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchaseOrderSetListGenerated.onTable().iCheckRows();
            When.onThePurchaseOrderSetListGenerated.onTable().iPressRow(0);

            Then.onThePurchaseOrderSetObjectPageGenerated.iSeeThisPage();
            Then.onThePurchaseOrderSetObjectPageGenerated.onTable({ property: "Items" }).iCheckRows();
            When.onThePurchaseOrderSetObjectPageGenerated.onTable({ property: "Items" }).iPressRow(0);

            Then.onThePurchaseOrderItemSetObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckNumberOfSections(2);
            When.onThePurchaseOrderItemSetObjectPageGenerated.iPressSectionIconTabFilterButton("ItemGeneralInformation");
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSection({ section: "ItemGeneralInformation" });
            //When.onThePurchaseOrderItemSetObjectPageGenerated.iGoToSection({ section: "ItemGeneralInformation", subSection: "ItemDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSubSection({ section: "ItemDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemDetails" }).iCheckField({ property: "NODE_KEY" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemDetails" }).iCheckField({ property: "PARENT_KEY_NODE_KEY" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemDetails" }).iCheckField({ property: "PO_ITEM_POS" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemDetails" }).iCheckField({ property: "PRODUCT_GUID_NODE_KEY" });
            //When.onThePurchaseOrderItemSetObjectPageGenerated.iGoToSection({ section: "ItemGeneralInformation", subSection: "ItemPricingDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSubSection({ section: "ItemPricingDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemPricingDetails" }).iCheckField({ property: "GROSS_AMOUNT" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemPricingDetails" }).iCheckField({ property: "NET_AMOUNT" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemPricingDetails" }).iCheckField({ property: "TAX_AMOUNT" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ItemPricingDetails" }).iCheckField({ property: "CURRENCY_code" });
            When.onThePurchaseOrderItemSetObjectPageGenerated.iPressSectionIconTabFilterButton("ProductInformation");
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSection({ section: "ProductInformation" });
            //When.onThePurchaseOrderItemSetObjectPageGenerated.iGoToSection({ section: "ProductInformation", subSection: "ProductDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSubSection({ section: "ProductDetails" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/ProductId" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/ProductName" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/Category" });
            //When.onThePurchaseOrderItemSetObjectPageGenerated.iGoToSection({ section: "ProductInformation", subSection: "ProductPricing" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSubSection({ section: "ProductPricing" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ProductPricing" }).iCheckField({ property: "PRODUCT_GUID/Price" });
            //When.onThePurchaseOrderItemSetObjectPageGenerated.iGoToSection({ section: "ProductInformation", subSection: "ProductDimensions" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.iCheckSubSection({ section: "ProductDimensions" });
            Then.onThePurchaseOrderItemSetObjectPageGenerated.onForm({ section: "ProductDimensions" }).iCheckField({ property: "PRODUCT_GUID" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});