/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrderSetListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePurchaseOrderSetListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "PO_ID" });
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "PARTNER_GUID/COMPANY_NAME" });
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "PARTNER_GUID/ADDRESS_GUID/COUNTRY" });
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "GROSS_AMOUNT" });
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "CURRENCY_code" });
            Then.onThePurchaseOrderSetListGenerated.onFilterBar().iCheckFilterField({ property: "OVERALL_STATUS" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePurchaseOrderSetListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePurchaseOrderSetListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iPressAction("Boost PO Gross Amount");
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckAction("Boost PO Gross Amount", { enabled: false });
            // When.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iPressAction("Copy Purchase Order");
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckAction("Copy Purchase Order", { enabled: false });
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"PO_ID":{"header":"Purchase Order ID"},"PARTNER_GUID/COMPANY_NAME":{"header":"Company Name"},"PARTNER_GUID/ADDRESS_GUID/COUNTRY":{"header":"Country"},"GROSS_AMOUNT":{"header":"Gross Amount"},"CURRENCY_code":{"header":"Currency"},"OverallStatusText":{"header":"Overall Status Text"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThePurchaseOrderSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThePurchaseOrderSetListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThePurchaseOrderSetObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});