/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrderSetObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseOrderSetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePurchaseOrderSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchaseOrderSetListGenerated.onTable().iCheckRows();
            When.onThePurchaseOrderSetListGenerated.onTable().iPressRow(0);

            Then.onThePurchaseOrderSetObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onThePurchaseOrderSetObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onThePurchaseOrderSetObjectPageGenerated.onHeader().iPressEdit();
            Then.onThePurchaseOrderSetObjectPageGenerated.onHeader().iCheckAction({ service: "CatalogService", action: "setApproved", unbound: false }, { enabled: false });
            // When.onThePurchaseOrderSetObjectPageGenerated.onHeader().iPressAction({ service: "CatalogService", action: "setApproved", unbound: false });
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckNumberOfSections(2);
            When.onThePurchaseOrderSetObjectPageGenerated.iPressSectionIconTabFilterButton("Facets::0");
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckSection({ section: "Facets::0" });
            //When.onThePurchaseOrderSetObjectPageGenerated.iGoToSection({ section: "Facets::0", subSection: "Identification" });
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckSubSection({ section: "Identification" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "PO_ID" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "PARTNER_GUID_NODE_KEY" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "LIFECYCLE_STATUS" });
            //When.onThePurchaseOrderSetObjectPageGenerated.iGoToSection({ section: "Facets::0", subSection: "FieldGroup::Pricing" });
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::Pricing" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "GROSS_AMOUNT" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "NET_AMOUNT" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "TAX_AMOUNT" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "CURRENCY_code" });
            //When.onThePurchaseOrderSetObjectPageGenerated.iGoToSection({ section: "Facets::0", subSection: "FieldGroup::Status" });
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::Status" });
            Then.onThePurchaseOrderSetObjectPageGenerated.onForm({ section: "FieldGroup::Status" }).iCheckField({ property: "OVERALL_STATUS" });
            When.onThePurchaseOrderSetObjectPageGenerated.iPressSectionIconTabFilterButton("Items::LineItem");
            Then.onThePurchaseOrderSetObjectPageGenerated.iCheckSection({ section: "Items::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});